In [ ]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)

Pandas version: 3.0.1
NumPy version: 2.4.2

In [ ]:
DATA_PATH = (
    r"D:\UPI_Fraud_Detection_Project_ML\data\upi_fraud_detection_dataset_100k.csv"
)

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Dataset loaded successfully!
Rows: 100000
Columns: 22

In [3]:
df.head()

,transaction_id,user_id,timestamp,amount,merchant_category,transaction_type,sender_bank,receiver_bank,device_type,os,...,device_trust_score,failed_attempts,transaction_velocity,account_age_days,is_new_device,is_new_location,beneficiary_age_days,hour,is_weekend,is_fraud
0,TXN00000001,USR001339,2026-07-20 17:27:54,154.25,Food,Bill Payment,Kotak,SBI,Android,Android 15,...,91.88,0,4,2472,0,0,932,17,0,0
1,TXN00000002,USR011610,2026-08-29 20:08:54,102.42,Utilities,Bill Payment,Axis,Kotak,Android,Android 14,...,96.16,0,2,163,0,0,1166,20,1,0
2,TXN00000003,USR009819,2026-06-06 02:13:15,324.43,Travel,Merchant Payment,IDFC First,Kotak,Android,Android 15,...,77.42,1,2,368,0,0,392,2,1,0
3,TXN00000004,USR006584,2026-04-24 00:45:32,42.56,Shopping,Merchant Payment,IndusInd,IDFC First,Android,Android 14,...,96.22,1,3,953,0,1,490,0,0,0
4,TXN00000005,USR006496,2026-01-02 06:16:25,42.32,Education,Bank Transfer,IndusInd,ICICI,Android,Android 15,...,69.86,0,2,104,0,0,665,6,0,0

In [4]:
df.tail()

,transaction_id,user_id,timestamp,amount,merchant_category,transaction_type,sender_bank,receiver_bank,device_type,os,...,device_trust_score,failed_attempts,transaction_velocity,account_age_days,is_new_device,is_new_location,beneficiary_age_days,hour,is_weekend,is_fraud
99995,TXN00099996,USR014783,2026-06-17 13:31:11,80.13,Fuel,P2P,HDFC,HDFC,iOS,iOS 18,...,96.13,0,1,2498,0,0,1334,13,0,0
99996,TXN00099997,USR000262,2026-09-06 23:52:58,296.46,Entertainment,P2P,IDFC First,Axis,Android,Android 14,...,54.98,2,2,300,0,0,457,23,1,0
99997,TXN00099998,USR008617,2026-07-19 14:30:26,24.57,Education,P2P,SBI,IDFC First,Android,Android 15,...,75.09,1,4,1185,0,0,633,14,1,0
99998,TXN00099999,USR000079,2026-07-03 15:30:29,38.84,Electronics,Recharge,IndusInd,Yes Bank,Android,Android 15,...,96.98,1,1,2314,0,0,1421,15,0,0
99999,TXN00100000,USR014059,2026-05-21 10:39:29,201.57,Healthcare,P2P,Kotak,IndusInd,Android,Android 15,...,80.60,0,1,1386,0,0,1231,10,0,0

In [5]:
print("Total Columns:", len(df.columns))

for i, col in enumerate(df.columns, start=1):
    print(f"{i}. {col}")

Total Columns: 22
1. transaction_id
2. user_id
3. timestamp
4. amount
5. merchant_category
6. transaction_type
7. sender_bank
8. receiver_bank
9. device_type
10. os
11. location
12. ip_risk_score
13. device_trust_score
14. failed_attempts
15. transaction_velocity
16. account_age_days
17. is_new_device
18. is_new_location
19. beneficiary_age_days
20. hour
21. is_weekend
22. is_fraud

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        100000 non-null  str
 1   user_id               100000 non-null  str
 2   timestamp             100000 non-null  str
 3   amount                100000 non-null  float64
 4   merchant_category     100000 non-null  str
 5   transaction_type      100000 non-null  str
 6   sender_bank           100000 non-null  str
 7   receiver_bank         100000 non-null  str
 8   device_type           100000 non-null  str
 9   os                    100000 non-null  str
 10  location              100000 non-null  str
 11  ip_risk_score         100000 non-null  float64
 12  device_trust_score    100000 non-null  float64
 13  failed_attempts       100000 non-null  int64
 14  transaction_velocity  100000 non-null  int64
 15  account_age_days      100000 non-null  int64
 16  is_new_device         100000 non-null  int64
 17  is_new_location       100000 non-null  int64
 18  beneficiary_age_days  100000 non-null  int64
 19  hour                  100000 non-null  int64
 20  is_weekend            100000 non-null  int64
 21  is_fraud              100000 non-null  int64
dtypes: float64(3), int64(9), str(10)
memory usage: 16.8 MB

In [ ]:
missing = pd.DataFrame(
    {
        "Missing_Count": df.isnull().sum(),
        "Missing_Percentage": (df.isnull().sum() / len(df) * 100).round(2),
    }
)

missing[missing["Missing_Count"] > 0]

Empty DataFrame
Columns: [Missing_Count, Missing_Percentage]
Index: []

In [8]:
print("duplicate rows:", df.duplicated().sum())

duplicate rows: 0

In [ ]:
[
    col
    for col in df.columns
    if any(word in col.lower() for word in ["fraud", "is_fraud", "target", "Label"])
]

['is_fraud']

In [10]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
transaction_id,100000,100000,TXN00000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
user_id,100000,14984,USR007171,18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
timestamp,100000,99775,2026-06-13 08:51:12,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amount,100000.0,NaN,NaN,NaN,1240.067402,9890.515424,10.0,76.3575,150.98,301.24,149861.79
merchant_category,100000,12,Utilities,8462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_type,100000,5,P2P,35029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sender_bank,100000,10,Axis,10147,NaN,NaN,NaN,NaN,NaN,NaN,NaN
receiver_bank,100000,10,IDFC First,10135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
device_type,100000,3,Android,65156,NaN,NaN,NaN,NaN,NaN,NaN,NaN
os,100000,4,Android 15,35983,NaN,NaN,NaN,NaN,NaN,NaN,NaN
location,100000,12,Pune,18037,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ip_risk_score,100000.0,NaN,NaN,NaN,20.807234,14.233523,0.08,10.79,18.1,27.64,99.98
device_trust_score,100000.0,NaN,NaN,NaN,79.170449,14.073511,0.03,72.37,81.8,89.12,99.94
failed_attempts,100000.0,NaN,NaN,NaN,0.40797,0.800485,0.0,0.0,0.0,1.0,7.0
transaction_velocity,100000.0,NaN,NaN,NaN,2.30683,1.804111,0.0,1.0,2.0,3.0,15.0
account_age_days,100000.0,NaN,NaN,NaN,1265.62721,712.76276,30.0,648.0,1266.0,1885.0,2499.0
is_new_device,100000.0,NaN,NaN,NaN,0.09141,0.288193,0.0,0.0,0.0,0.0,1.0
is_new_location,100000.0,NaN,NaN,NaN,0.11145,0.31469,0.0,0.0,0.0,0.0,1.0
beneficiary_age_days,100000.0,NaN,NaN,NaN,740.27429,436.790967,1.0,364.0,739.0,1119.0,1499.0
hour,100000.0,NaN,NaN,NaN,11.46421,6.900142,0.0,6.0,11.0,17.0,23.0
is_weekend,100000.0,NaN,NaN,NaN,0.28419,0.45103,0.0,0.0,0.0,1.0,1.0
is_fraud,100000.0,NaN,NaN,NaN,0.01588,0.125012,0.0,0.0,0.0,0.0,1.0

In [11]:
df.columns.tolist()

['transaction_id',
 'user_id',
 'timestamp',
 'amount',
 'merchant_category',
 'transaction_type',
 'sender_bank',
 'receiver_bank',
 'device_type',
 'os',
 'location',
 'ip_risk_score',
 'device_trust_score',
 'failed_attempts',
 'transaction_velocity',
 'account_age_days',
 'is_new_device',
 'is_new_location',
 'beneficiary_age_days',
 'hour',
 'is_weekend',
 'is_fraud']

In [12]:
print(f"Rows: {df.shape[0]:,}")
print(f"Columns: {df.shape[1]}")
print(f"Memory Usage: {df.memory_usage(deep=True).sum() / 1024**2:.2f}MB")

Rows: 100,000
Columns: 22
Memory Usage: 64.49MB

In [ ]:
pd.DataFrame(
    {
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str),
        "Unique_Values": [df[col].nunique() for col in df.columns],
        "Missing_Values": [df[col].isna().sum() for col in df.columns],
    }
)

,Column,Data_Type,Unique_Values,Missing_Values
transaction_id,transaction_id,str,100000,0
user_id,user_id,str,14984,0
timestamp,timestamp,str,99775,0
amount,amount,float64,46087,0
merchant_category,merchant_category,str,12,0
transaction_type,transaction_type,str,5,0
sender_bank,sender_bank,str,10,0
receiver_bank,receiver_bank,str,10,0
device_type,device_type,str,3,0
os,os,str,4,0
location,location,str,12,0
ip_risk_score,ip_risk_score,float64,6935,0
device_trust_score,device_trust_score,float64,7007,0
failed_attempts,failed_attempts,int64,8,0
transaction_velocity,transaction_velocity,int64,16,0
account_age_days,account_age_days,int64,2470,0
is_new_device,is_new_device,int64,2,0
is_new_location,is_new_location,int64,2,0
beneficiary_age_days,beneficiary_age_days,int64,1499,0
hour,hour,int64,24,0
is_weekend,is_weekend,int64,2,0
is_fraud,is_fraud,int64,2,0

In [14]:
fraud_counts = df["is_fraud"].value_counts()

print(fraud_counts)

print("\nFraud Percentage:")
print((df["is_fraud"].value_counts(normalize=True) * 100).round(2))

is_fraud
0    98412
1     1588
Name: count, dtype: int64

Fraud Percentage:
is_fraud
0    98.41
1     1.59
Name: proportion, dtype: float64

In [ ]:
df.groupby("is_fraud")["amount"].agg(["count", "mean", "median", "min", "max"]).round(2)

          count      mean    median   min        max
is_fraud
0         98412    246.93    148.74  10.0   21878.86
1          1588  62786.80  61878.75  10.0  149861.79

In [16]:
numerical_cols = df.select_dtypes(include=np.number).columns.tolist()

print("Numerical columns:")
print(numerical_cols)

Numerical columns:
['amount', 'ip_risk_score', 'device_trust_score', 'failed_attempts', 'transaction_velocity', 'account_age_days', 'is_new_device', 'is_new_location', 'beneficiary_age_days', 'hour', 'is_weekend', 'is_fraud']

In [17]:
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

print("Categorical columns:")
print(categorical_cols)

Categorical columns:
['transaction_id', 'user_id', 'timestamp', 'merchant_category', 'transaction_type', 'sender_bank', 'receiver_bank', 'device_type', 'os', 'location']

C:\Users\Munde Mahesh\AppData\Local\Temp\ipykernel_12304\154499198.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

In [18]:
print("Duplicate transaction IDs:", df["transaction_id"].duplicated().sum())
print("Duplicate user IDs:", df["user_id"].duplicated().sum())

Duplicate transaction IDs: 0
Duplicate user IDs: 85016

In [19]:
print("Timestamp datatype:", df["timestamp"].dtype)

print("\nFirst timestamp:")
print(df["timestamp"].min())

print("\nLast timestamp:")
print(df["timestamp"].max())

Timestamp datatype: str

First timestamp:
2026-01-01 00:05:13

Last timestamp:
2026-09-30 23:43:57

In [20]:
fraud_rate = df["is_fraud"].mean() * 100

print(f"Overall Fraud Rate: {fraud_rate:.2f}%")

Overall Fraud Rate: 1.59%